### PR TITLE
Made a better README

### LINKED ISSUE #51: Make a better Readme
Hi again 👋

I think it would be better to have a readme that explains more about the project than the default readme.

If this is approved I would love to work on this.

### PR DESCRIPTION
**Pull request by jessej-samuel**
Fixes #51 

@thekavikumar  lmk if you want something changed or added!

### CODE REVIEW

**Review by thekavikumar — CHANGES_REQUESTED** [review]
Will you be able to create something like this https://github.com/amplication/amplication#readme

**Comment by jessej-samuel** [comment]
@thekavikumar do you mean like adding the contributors names? Also if you want me to add the features, lmk what other cool features this project has :)

**Comment by thekavikumar** [comment]
image
I would like to have a feature that is marked. I mean the picture, techs used badges on the top
image
you can add the marked features.
image
You can add a section "how to contribute" having all steps to set up the project in their local env.
image
You can add the new feature request section
Also if possible you can add the contributors' images and all.

**Comment by jessej-samuel** [comment]
Ah cool

**Review by thekavikumar — CHANGES_REQUESTED** [review]
Add this image instead of the banner
image

**Comment by jessej-samuel** [comment]
@thekavikumar I am done

**Review by thekavikumar — APPROVED** [review]
Great job dude :)

**Pull request merged**
